# AI Model related settings
selected_model: yolo11s.pt                     # model to be used (only name)
region_bbox: [370, 30, 630, 200]               # region of interest (x1, y1, x2, y2)

# Frame selection related settings
frame_selection_mechanism: denominator         # [denominator or range] = every nth frame or absolute frame range [start, end]
denominator: 1                                 # 1 = every frame, 2 = every other frame, etc.
range: [40, 200]                               # frames to be processed [start, end]
  
# Miscellaneous settings
vizualize_inference: True                      # visualize the inference results
retention_time: 30                             # (~1 seocnd) frames to keep the last item_scan
vizualization_cooldown_time: 60                # (~2 seconds) frames to wait before vizualizing the inference results